import React from "react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-4xl mx-auto px-6 py-20">
        <h1 className="text-5xl font-black text-gray-900 tracking-tighter mb-8 uppercase">Terms of <span className="text-blue-600">Service</span></h1>
        
        <div className="prose prose-slate max-w-none">
          <p className="text-gray-500 mb-12">Last Updated: June 7, 2026</p>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Acceptance of Terms</h2>
            <p className="text-gray-600">
              By accessing or using YoflowAI, you agree to be bound by these Terms of Service.
            </p>
          </section>

          <section className="mb-12 bg-orange-50 p-8 rounded-3xl border border-orange-100">
            <h2 className="text-2xl font-bold text-orange-900 mb-4 flex items-center gap-2">
              <svg className="w-6 h-6 text-orange-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
              Medical Disclaimer
            </h2>
            <p className="text-orange-800 font-medium">
              YoflowAI is not a medical professional. The yoga flows generated are for educational and fitness purposes only. Consult with a physician before beginning any new exercise program. Use of the service is at your own risk.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Use of Service</h2>
            <p className="text-gray-600">
              You are responsible for your own safety and for ensuring that the space in which you practice is safe. Always listen to your body and never force a position that causes pain.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">3. AI-Generated Content</h2>
            <p className="text-gray-600">
              Sequences and images are generated by AI. While we strive for accuracy, YoflowAI does not guarantee the correctness or anatomical precision of every generated detail.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
